### ISSUE TITLE
Benchmark failed with error code 6 - Hyperledger Besu

### ISSUE THREAD

**Issue by farhanajaved** [hyperledger-caliper/caliper-benchmarks#256]
caliper launch manager     --caliper-workspace /home/linuxbrew/.linuxbrew/Caliper-config --caliper-benchconfig /home/linuxbrew/.linuxbrew/Caliper-config/benchmarks/bench1.yml --caliper-networkconfig /home/linuxbrew/.linuxbrew/Caliper-config/besu-config.yml
2023.09.29-21:42:59.727 info  [caliper] [cli-launch-manager]    Set workspace path: /home/linuxbrew/.linuxbrew/Caliper-config
2023.09.29-21:42:59.727 info  [caliper] [cli-launch-manager]    Set benchmark configuration path: /home/linuxbrew/.linuxbrew/Caliper-config/benchmarks/bench1.yml
2023.09.29-21:42:59.727 info  [caliper] [cli-launch-manager]    Set network configuration path: /home/linuxbrew/.linuxbrew/Caliper-config/besu-config.yml
2023.09.29-21:42:59.727 info  [caliper] [cli-launch-manager]    Set SUT type: ethereum
2023.09.29-21:42:59.849 info  [caliper] [benchmark-validator]   No observer specified, will default to `none`
2023.09.29-21:42:59.850 info  [caliper] [caliper-engine]        Starting benchmark flow
2023.09.29-21:42:59.850 info  [caliper] [caliper-engine]        Network configuration attribute "caliper.command.start" is not present, skipping start command
2023.09.29-21:42:59.855 error [caliper] [caliper-engine]        Error while performing "test" step: /home/linuxbrew/.linuxbrew/Caliper-config/besu-config.yml:7
    - name: SimpleStorage
          ^

SyntaxError: Unexpected token ':'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at new EthereumConnector (/usr/lib/node_modules/@hyperledger/caliper-cli/node_modules/@hyperledger/caliper-ethereum/lib/ethereum-connector.js:47:30)
    at CaliperEngine.connectorFactory [as adapterFactory] (/usr/lib/node_modules/@hyperledger/caliper-cli/node_modules/@hyperledger/caliper-ethereum/lib/connectorFactory.js:26:12)
    at CaliperEngine.run (/usr/lib/node_modules/@hyperledger/caliper-cli/node_modules/@hyperledger/caliper-core/lib/manager/caliper-engine.js:109:64)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LaunchManager.handler (/usr/lib/node_modules/@hyperledger/caliper-cli/lib/launch/lib/launchManager.js:62:30)
2023.09.29-21:42:59.855 info  [caliper] [caliper-engine]        Network configuration attribute "caliper.command.end" is not present, skipping end command
2023.09.29-21:42:59.855 error [caliper] [cli-launch-manager]    Benchmark failed with error code 6
Usage:
 caliper launch manager --caliper-bind-sut fabric:2.2 [other options]

Options:
  --help, -h           Show usage information  [boolean]
  --version            Show version information  [boolean]
  --caliper-bind-sut   The name and version of the platform to bind to  [string]
  --caliper-bind-cwd   The working directory for performing the SDK install  [string]
  --caliper-bind-args  Additional arguments to pass to "npm install". Use the "=" notation when setting this parameter  [string]
  --caliper-bind-file  Yaml file to override default (supported) package versions when binding an SDK  [string]

Error: Benchmark failed with error code 6
    at LaunchManager.handler (/usr/lib/node_modules/@hyperledger/caliper-cli/lib/launch/lib/launchManager.js:70:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    
    
  I am not able to find the issue exactly here

**Comment by davidkel** [comment]
Closing as we have had to drop ethereum and besu support so subsequently we are dropping the benchmarks as well
